version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 14
    commands:
      - npm install -g create-react-app
  pre_build:
    commands:
      - cd ./frontend
      - npm install
      - npm install react-quill
  build:
    commands:
      - npm run build
artifacts:
  base-directory: frontend/build/
  files: 
    - '**/*'
